### ISSUE TITLE
Key extraction from Kamstrup Wireless MBus Dongle

### ISSUE THREAD

**Issue by PatrickAmann** [wmbusmeters/wmbusmeters#1236]
Since my local water company wont provide the key but offered to get a wireless M bus dongle configured by kamstrup directly to be used with my water meter, I was wondering if the key can somehow be extracted from this OEM dongle?

The kamstrup software describes a function to "Get Meter X Settings" (left screenshot on the bottom left):

https://documentation.kamstrup.com/docs/Wireless_M_Bus_Dongle/en-GB/User_guide/CONT74D29DEC0A39465BB9DA4221045D4C02/?page=10

This makes me wonder if the key can be extracted by either using this method or some other methods since I dont feel like using a second dongle for the exact same thing as my other one already does. Especially if that single Meter-configured Dongle is 230 bucks.

**Comment by weetmuts** [comment]
I do not think that it is practically possible to extract the key. However I know for sure that a user has successfully used wmbusmeters to query the mbus dongle to get the meter readings. You need an mbus master that can supply enough power though since the dongle pulls a bit more energy from the m-bus than a normal meter.

Lasse did write a short text describing how to do this, which I have attached. Thanks Lasse!
I is meant to go to the wiki eventually.
[Kamstrup_wmbus_to_mbus_dongle.pdf](https://github.com/wmbusmeters/wmbusmeters/files/14914262/Kamstrup_wmbus_to_mbus_dongle.pdf)
