### ISSUE TITLE
Techem Heatmeter Typ 4.1.1 - Couldn't get temperature and volume flow

### ISSUE THREAD

**Issue by swing7** [wmbusmeters/wmbusmeters#1258]
### Type of request

Question

### OS version

Frontend

### wmbusmeters version

1.16.1-23-gefcc41d

### Your message goes here

Hi Fredrik,

Thanks for wonderful contribution to wMbus space. 

I have a concern regarding Techem Typ 4.1.1 as:
- We have received 2 telegrams and we have respective 2 AES keys but couldn't get temperature and volume flow
-  Using wmbusmeters.org to test with multiple drivers

- Telegram & AES
   - Telegram1: 434468503344506728048c2039900f002c250df21400b11f9b4964f603ec7aff002007100d259d3d2222194dff842b3e804e9b322b428298c711b42229d2b4fb518f4e13
   - AES1: 58DF4958FA0BBF93BD3399BD726C62CE

   - Telegram 2: 6e4468503344506728048c0039900f002c250ef2140070c21c05e56cb4f37aff004007103ee992f4138b0c6022ef8f800418f2a1fe69a578f441e3f75522119f570eeb6d1a0605b1607ee5f695880d8d79af6ce66ac2a6cac11343f1967caefb0fde159c0fa6bcfd4dd5fb25e14b46
   - AES2: 63FA1FF5029A28F3BE7E59EC84263531

On running them through multiple drivers, we found just Energy but not temperature and volume. 

Could you please help us to understand if we are missing something or which driver would help to get these?

Thanks in advance!

**Comment by hdssdh** [comment]
I came across the same problem. Telegram 2 can be decoded with the AES2 key, The decoded payload seems to be again encrypted (Manufacturer specific data), because I could not find any data that changes steadily with changing temperature/flow in subsequent telegrams. A Techem rep. said that Telegram 2 contains proprietry data. One can only read Telegram 1 containing consumed energy. I guess that Telegram 2 may contain temeperatures and flow data. @swing7 did you find further information?

**Comment by swing7** [comment]
Hey @hdssdh! As you correctly found, there is no way to read Telegram 2 because it contains proprietary data. 

PS: Having worked with several meters, I found Techem as the worst considering documentation and support.
