### ISSUE TITLE
CYBLE GT3-ITR

### ISSUE THREAD

**Issue by Anas92230** [wmbusmeters/wmbusmeters#1284]
### Type of request

Question

### OS version

Ubuntu

### wmbusmeters version

1.16.1-29-g1a4169e

### Your message goes here

Hello,
Veolia change my watermater with :
-CYBLE G3-ITR
868MHZ
Birdz-Veolia G3 Technology
I hope that this device is supported :-)
I use this command : 
  - wmbusmeters --logtelegrams --verbose auto:t1 => nothing
If you have an idea :-)
Thanks

**Comment by famillenounoux** [comment]
+1

**Comment by benisr007** [comment]
+1

**Comment by Anas92230** [comment]
Hi @weetmuts,
did you ever seen this watermater :-)?
thanks for help

**Comment by toff63** [comment]
Based on this ["Product Specification"](https://www.birdz.com/wp-content/uploads/2022/06/G3-FP.pdf), it looks like this is the same as issue #479 . TLDR; you need a lorawan dongle like iU880B, use `:lora` instead of `t1` and pray for Veolia to not use encryption. I am curious about your findings as I have the same at home.

**Comment by xamyp** [comment]
hello @Anas92230 @famillenounoux did you solve the problem because I am in the same situation ?
