### ISSUE TITLE
HA-addon : log directroy meter_reading empty

### ISSUE THREAD

**Issue by chpego** [wmbusmeters/wmbusmeters#767]
### Discussed in https://github.com/weetmuts/wmbusmeters/discussions/760

<div type='discussions-op-text'>

<sup>Originally posted by **chpego** December 21, 2022</sup>
Hi guys !

I'm curious, but i'm looking for logs of the daemon wmbusmeters:
But there is no log, because in this line, you're using useconfig options
https://github.com/weetmuts/wmbusmeters/blob/f992c9f8107d2766c72f9dcb3aa51f6360b50131/ha-addon/run.sh#L60
and accordling with [this](https://github.com/weetmuts/wmbusmeters#run-using-config-files) , we cannot use this few options:
> The option `--useconfig=` can only be combined with a few other options: `--overridedevice= --listento= --exitafter= --oneshot= --silent --normal --verbose --debug --trace`

So the directory logs/meter_readings is empty, maybe adding this in **run.sh** can help to have logs of meter:
``
echo -e "meterfiles=$CONFIG_DATA_PATH/logs/meter_readings" >> $CONFIG_DATA_PATH/etc/wmbusmeters.conf
``

What do you think?</div>

**Comment by BIBOLV** [comment]
HA add-on has moved to separate repo - https://github.com/wmbusmeters/wmbusmeters-ha-addon
It has now pre-built container images and config interface changes - please test and close this issue if no other questions.

But what would be use case for having meter readings in file, because all logs are being sent to HA and they are available from HA side, but readings are meant to be sent to mqtt to display in HA.
