### ISSUE TITLE
Misleading wmbusmeters analyzer.

### ISSUE THREAD

**Issue by SzczepanLeon** [wmbusmeters/wmbusmeters#890]
### Type of request

Bug

### OS version

web

### wmbusmeters version

latest

### Your message goes here

Seems that analyzer is not accurate with A-field.

As I understand first column is position (start) in telegram:
```
000   : 19 length (25 bytes)
001   : 44 dll-c (from meter SND_NR)
002   : 304c dll-mfct (SAP)
004   : 58dcb800 dll-id (00b8dc58)
008   : 00 dll-version
009   : 07 dll-type (Water meter)
010   : a2 tpl-ci-field (Mfct specific)
```

so for example dll-c is second byte from telegram

I have telegram like [this](https://wmbusmeters.org/analyze/1944304c58dcB8008800a2710800133ea3faa2B4028f4c4B4eBe) and dll-id position is marked as **004**. This is OK. But for telegram like [this](https://wmbusmeters.org/analyze/1944A511780743434418A241150013CE0766324C94EE48EEF6C8) dll-id is also marked as **004**, but in telegram it starts from **006**.

**Comment by weetmuts** [comment]
Hmm, the telegrams look both correct, the first with mftct SAP is the old version of the izar meter where
the id at offset 4, is a non-wmbus-conformant hex id, this telegram contains the human readable serial-number inside the mfct specific data. 

The new version of the izar (from Diehl DME that bougth SAP Sappel) meter does not need that since it uses the dll-id in a wmbus-conformant way (which is part of the dll-address fields) as presented in the header at offset 4.
